all: 5a 5b 5c 5d 5e 5f 5g 5h

clean:
	rm -f 5a 5b 5c 5d 5e 5f 5g 5h

5a: 5a.c
	gcc -o 5a 5a.c -Wall
5b: 5b.c
	gcc -o 5b 5b.c -Wall
5c: 5c.c
	gcc -o 5c 5c.c -Wall
5d: 5d.c
	gcc -o 5d 5d.c -Wall
5e: 5e.c
	gcc -o 5e 5e.c -Wall
5f:	5f.c
	gcc -o 5f 5f.c -Wall
5g:	5g.c
	gcc -o 5g 5g.c -Wall
5h: 5h.c
	gcc -o 5h 5h.c -Wall